### ISSUE TITLE
Container provided for tomcat/jmx does not start

### ISSUE THREAD

**Issue by mihai-tarabuta-yt** [aws-observability/aws-otel-collector-test-framework#1386]
Please see attached trace for trying to stand up the container in a local environment.
The same behavior exists when the sample app is deployed to EKS via ECR.

Tomcat starts fine when instrumentation agent is not set. When set it fails with the below [error](url)

Could not load Logmanager "org.apache.juli.ClassLoaderLogManager"
java.lang.ClassNotFoundException: org.apache.juli.ClassLoaderLogManager
....

[sample-appa-jmx-build-and-run-test.txt](https://github.com/aws-observability/aws-otel-test-framework/files/12374761/sample-appa-jmx-build-and-run-test.txt)

**Comment by rapphil** [comment]
Hi, 

Can you try to build the image on a Linux machine instead of Windows? I tried locally and it works on Linux. Since you are going to deploy to ECR, can you build/push the image from a Linux machine?

**Comment by mihai-tarabuta-yt** [comment]
A colleague of mine did the build on a Mac and it worked fine on local and in the EKS via ECR. So I guess the issue may be with the Windows environment
