### ISSUE TITLE
Image does not exist

### ISSUE THREAD

**Issue by CorbyAsCode** [aws-observability/aws-otel-collector-test-framework#148]
While trying to run examples/docker-compose.yml I got this error message:
    Pulling ot-sample-app (mxiamxia/aws-otel-collector-java-sample-app:0.4.0)...
    ERROR: pull access denied for mxiamxia/aws-otel-collector-java-sample-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by wyTrivail** [comment]
duplicate issue in the collector repo.
