### ISSUE TITLE
Allow reading expected test templates from files

### ISSUE THREAD

**Issue by anuraaga** [aws-observability/aws-otel-collector-test-framework#227]
Currently, all expectations are in resources in this repo. But since sample apps and tested instrumentations are in different repos, really the expectations should live there too - when updating an app and something breaks, we fix the apps and tests at the same time.

**Comment by wyTrivail** [comment]
@mxiamxia @vastin @pxaws

**Comment by anuraaga** [comment]
@mxiamxia @wyTrivail @vastin @pxaws Is it possible to prioritize this issue? It will be quite helpful, for example for projects like the lambda repo.

**Comment by wyTrivail** [comment]
@anuraaga  sorry for my late,  finally got some times to work on it. 

https://github.com/aws-observability/aws-otel-test-framework/pull/295/files
