### ISSUE TITLE
Publish validator as a docker image

### ISSUE THREAD

**Issue by anuraaga** [aws-observability/aws-otel-collector-test-framework#228]
Right now, our workflows generally have three steps, one to docker-compose up the collector, one to docker run a sample app, and one to gradlew run the test validator. We should just publish docker images of the validator so this can be a single docker-compose command. The best result of this is that log messages of all three components will be properly visible.

**Comment by wyTrivail** [comment]
@mxiamxia @vastin

**Comment by pingleig** [comment]
I think this is already done w/ jib?
