### ISSUE TITLE
Update the user guide documents for running the soaking tests

### ISSUE THREAD

**Issue by mxiamxia** [aws-observability/aws-otel-collector-test-framework#249]
Will need to update the user guide documents for running the soaking tests. Currently, it just tells how to setup test framework generally

**Comment by pingleig** [comment]
I guess it's similar to canary https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/docs/run-testing-framework.md#25-run-in-canary 

We might want to specify how to pass parameters, though people can look at existing github action config/log to figure that out.

btw: Is our github action log public to non members?

**Comment by at15** [comment]
Yep, the log from github action is public (this is comment is not from @pingleig 🐶

**Comment by vasireddy99** [comment]
Closing this issue based on these [steps available](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/docs/run-testing-framework.md#252-run-in-negative-soaking-test) in readme for the soak tests
