### ISSUE TITLE
[framework] Port resource clean up logic from deprecating branch

### ISSUE THREAD

**Issue by pingleig** [aws-observability/aws-otel-collector-test-framework#255]
terraform fails to delete resource for various reasons (e.g. test took too long and its k8s token is outdated, leaving namespace around).

- [ ] [ec2](https://github.com/aws-observability/aws-otel-test-framework/blob/deprecating/integ-test/src/main/java/com/amazon/aocagent/tasks/EC2Clean.java) 
- [ ] [eks namespace](https://github.com/aws-observability/aws-otel-test-framework/blob/deprecating/integ-test/src/main/java/com/amazon/aocagent/tasks/EKSClean.java)
- [ ] efs mount and efs file system

Most env setup logic is in tf, but it's hard to write resource clean up logic in tf. Further more we need to deal with problems like #253, which we are using shell script, I plan to write a go util to handle all those util tasks so it's easier to extend and maintain in the future.

**Comment by pingleig** [comment]
I think existing resource cleaner does not work because it can't match tag. And we didn't distinguish ec2 instances for canary and soaking, so it's hard to terminate instances. Until we are able to distinguish those there is no good way to clean up instances generated from CI.yaml ...

**Comment by vasireddy99** [comment]
Closing this issue by referencing to available [weekly resources](https://github.com/aws-observability/aws-otel-collector/blob/main/.github/workflows/weekly-resources-clean.yml#L36). Please re-open this issue if this is not the expected implementation.
