### ISSUE TITLE
Module layout for Container Insight integration tests

### ISSUE THREAD

**Issue by bjrara** [aws-observability/aws-otel-collector-test-framework#258]
When initiating integration tests for container insight in PR: https://github.com/aws-observability/aws-otel-test-framework/pull/247, we debated a lot on whether test cases should be merged into `/terraform/eks` or remain in a new folder `/terraform/containerinsight-eks-prometheus`.

This issue is created to keep track of the remaining tasks:
1. Merge `/terraform/containerinsight-eks-prometheus` into `/terraform/eks`. (PR in review)
2. Merge `CWMetricValidator` and `ContainerInsightMetricValidator`.
3. Provide design docs, and guidance for adding new test cases. 

Full history records can be found in https://github.com/aws-observability/aws-otel-test-framework/pull/247#issuecomment-810725653.

**Comment by wyTrivail** [comment]
thanks Mengyi! that's pretty good point we lack of design doc, i will put the design doc here later.

**Comment by pingleig** [comment]
I suppose it's done? And @wyTrivail is there any design doc? :doge:

**Comment by wyTrivail** [comment]
https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/docs/testing-framework-design.md
