### ISSUE TITLE
[Question]The task cannot be established in ECS

### ISSUE THREAD

**Issue by gavindoudou** [aws-observability/aws-otel-collector-test-framework#305]
I am running ECS test but it shows the ECS instance is not there: 
![image](https://user-images.githubusercontent.com/31523962/118724941-21a7be80-b7e4-11eb-890b-313bc12e194f.png)

It says that there is no container instance:
![image](https://user-images.githubusercontent.com/31523962/118725038-400dba00-b7e4-11eb-92d5-7eb6d91a9cbf.png)

But there are two instances in EC2 console:
![image](https://user-images.githubusercontent.com/31523962/118725089-4f8d0300-b7e4-11eb-9e29-aad54380b2bf.png)

It's not a bug because I could run successfully a few days ago when I tested my previous change. Just want to see does anyone encounter this problem? How to fix it on my side? Thanks!

**Comment by pingleig** [comment]
The ecs module we are using may not wait for ec2 instance to be up and running. Based on node name, the second one is the right instance, maybe something is wrong with ecs agent and it didn't join the cluster?  Can you ssh into the vm and check ecs agent log?
