### ISSUE TITLE
ADOT Logzio exporter support 

### ISSUE THREAD

**Issue by yotamloe** [aws-observability/aws-otel-collector-test-framework#338]
Logz.io has verified `logzio exporter` support using the ADOT collector `v0.12.0`.
sample usage:
```yaml
...
exporters:
  logzio:
    account_token: <<LOGZIO_TOKEN>>
    region: <<LOGZIO_REGION>>
...
```

We conducted performance tests as described [here](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/docs/get-performance-model.md#step-4-run-the-performance-test-and-get-the-performance-model)
Here are the results:
**100 tps:**
```json
{"testcase":"logzio_exporter_trace_mock","instanceType":"m5.2xlarge","receivers":["otlp"],"processors":["batch"],"exporters":["logzio"],"dataType":"otlp","dataMode":"trace","dataRate":100,"avgCpu":0.05555673328184996,"avgMem":59.660970666666664,"commitId":"dummy_commit","collectionPeriod":10,"testingAmi":"soaking_linux"}
```
**1000 tps:**
```json
{"testcase":"logzio_exporter_trace_mock","instanceType":"m5.2xlarge","receivers":["otlp"],"processors":["batch"],"exporters":["logzio"],"dataType":"otlp","dataMode":"trace","dataRate":1000,"avgCpu":0.0,"avgMem":0.0,"commitId":"dummy_commit","collectionPeriod":10,"testingAmi":"soaking_linux"}
```
**5000 tps:**
```json
{"testcase":"logzio_exporter_trace_mock","instanceType":"m5.2xlarge","receivers":["otlp"],"processors":["batch"],"exporters":["logzio"],"dataType":"otlp","dataMode":"trace","dataRate":5000,"avgCpu":0.04666626908009504,"avgMem":60.59281066666667,"commitId":"dummy_commit","collectionPeriod":10,"testingAmi":"soaking_linux"}
```

**Comment by mraditya** [comment]
There are newer releases of upstream [collector](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.35.0) and [contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.35.0) (v35) which might have breaking changes. Please rerun your tests with these weekly releases and publish your results per guidance [here](https://github.com/aws-observability/aws-otel-community/issues/35). We expect to have another release v36 (mid next week) which we aim to align with the stable release of tracing components. Please rerun tests for v36 version as well. We will notify you when v36 is ready for testing.

**Comment by mraditya** [comment]
OpenTelemetry Collection v0.36 is now available at https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.36.0
OpenTelemetry Collector Contrib v0.36 is now available at https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.36.0

**Comment by yotamloe** [comment]
@mraditya We Tested with the `v0.36.0` collector version, and its working well.
Here are the performance tests results with our real endpoint:
**100 tps:**
```json
{"testcase":"logzio_exporter_trace_mock","instanceType":"m5.2xlarge","receivers":["otlp"],"processors":["batch"],"exporters":["logzio"],"dataType":"otlp","dataMode":"trace","dataRate":100,"avgCpu":2.8309728032523056,"avgMem":87.817728,"commitId":"dummy_commit","collectionPeriod":10,"testingAmi":"soaking_linux"}
```
**1000 tps:**
```json
{"testcase":"logzio_exporter_trace_mock","instanceType":"m5.2xlarge","receivers":["otlp"],"processors":["batch"],"exporters":["logzio"],"dataType":"otlp","dataMode":"trace","dataRate":1000,"avgCpu":26.668528808717696,"avgMem":91.32003413333334,"commitId":"dummy_commit","collectionPeriod":10,"testingAmi":"soaking_linux"}
```
**5000 tps:**
```json
{"testcase":"logzio_exporter_trace_mock","instanceType":"m5.2xlarge","receivers":["otlp"],"processors":["batch"],"exporters":["logzio"],"dataType":"otlp","dataMode":"trace","dataRate":5000,"avgCpu":118.58227289186553,"avgMem":90.32933546666666,"commitId":"dummy_commit","collectionPeriod":10,"testingAmi":"soaking_linux"}
```

**Comment by vasireddy99** [comment]
Closing this issue as the expected results were submitted. Please reopen the issue for any questions/concerns
