### ISSUE TITLE
ADOT Datadog exporter traces support

### ISSUE THREAD

**Issue by mx-psi** [aws-observability/aws-otel-collector-test-framework#340]
Datadog has verified the `datadog` exporter traces support using the ADOT collector `v0.12.0`. Example usage:

```yaml
# ...
exporters:
  datadog:
    api:
      key: <<API KEY>>
      site: <<Datadog site>>

# ...
```

<details>
    <summary>100 TPS</summary>

```json
{
   "testcase":"datadog_exporter_trace_mock",
   "instanceType":"m5.2xlarge",
   "receivers":[
      "otlp"
   ],
   "processors":[
      "batch"
   ],
   "exporters":[
      "datadog"
   ],
   "dataType":"otlp",
   "dataMode":"trace",
   "dataRate":100,
   "avgCpu":7.970433210915003,
   "avgMem":72.67109546666667,
   "commitId":"dummy_commit",
   "collectionPeriod":10,
   "testingAmi":"soaking_linux"
}
```

</details>

<details>
    <summary>1000 TPS</summary>

```json
{
   "testcase":"datadog_exporter_trace_mock",
   "instanceType":"m5.2xlarge",
   "receivers":[
      "otlp"
   ],
   "processors":[
      "batch"
   ],
   "exporters":[
      "datadog"
   ],
   "dataType":"otlp",
   "dataMode":"trace",
   "dataRate":1000,
   "avgCpu":31.698562946404234,
   "avgMem":78.11624959999999,
   "commitId":"dummy_commit",
   "collectionPeriod":10,
   "testingAmi":"soaking_linux"
}
```
</details>

<details>
    <summary>5000 TPS</summary>

```json
{
   "testcase":"datadog_exporter_trace_mock",
   "instanceType":"m5.2xlarge",
   "receivers":[
      "otlp"
   ],
   "processors":[
      "batch"
   ],
   "exporters":[
      "datadog"
   ],
   "dataType":"otlp",
   "dataMode":"trace",
   "dataRate":5000,
   "avgCpu":113.51224673332504,
   "avgMem":92.87857493333334,
   "commitId":"dummy_commit",
   "collectionPeriod":10,
   "testingAmi":"soaking_linux"
}
```

</details>

We also conducted end to end testing to validate the behavior.

This supersedes aws-observability/aws-otel-collector#593.

**Comment by mraditya** [comment]
There are newer releases of upstream [collector](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.35.0) and [contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.35.0) (v35) which might have breaking changes. Please rerun your tests with these weekly releases and publish your results per guidance [here](https://github.com/aws-observability/aws-otel-community/issues/35). We expect to have another release v36 (mid next week) which we aim to align with the stable release of tracing components. Please rerun tests for v36 version as well. We will notify you when v36 is ready for testing.

**Comment by mx-psi** [comment]
Hi @mraditya we would need a new ADOT release that includes the new contrib release to do that

**Comment by mxiamxia** [comment]
Hi @mx-psi, ADOT `v0.12.0` is built upon OTel `v34` and it is a good to hear that your tests look good in this release. We'll  have ADOT release when `v36` is out from upstream. Will need your help to verify it again for Trace GA. Thanks!

**Comment by mx-psi** [comment]
Awesome, I will re-run the tests then to confirm that everything looks good :)

**Comment by mraditya** [comment]
OpenTelemetry Collection v0.36 is now available at https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.36.0
OpenTelemetry Collector Contrib v0.36 is now available at https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.36.0

**Comment by mx-psi** [comment]
Datadog has verified the `datadog` exporter traces support using the ADOT collector `v0.13.0` (commit aws-observability/aws-otel-collector@00843e063912bbed0c5fead4a61a2f2c49ea09c8) . Example usage:

```yaml
# ...
exporters:
  datadog:
    api:
      key: <<API KEY>>
      site: <<Datadog site>>

# ...
```

<details>
    <summary>100 TPS</summary>

```json
{
   "testcase":"datadog_exporter_trace_mock",
   "instanceType":"m5.2xlarge",
   "receivers":[
      "otlp"
   ],
   "processors":[
      "batch"
   ],
   "exporters":[
      "datadog"
   ],
   "dataType":"otlp",
   "dataMode":"trace",
   "dataRate":100,
   "avgCpu":6.670001403328118,
   "avgMem":69.41470720000002,
   "commitId":"dummy_commit",
   "collectionPeriod":10,
   "testingAmi":"soaking_linux"
}
```

</details>

<details>
    <summary>1000 TPS</summary>

```json
{
   "testcase":"datadog_exporter_trace_mock",
   "instanceType":"m5.2xlarge",
   "receivers":[
      "otlp"
   ],
   "processors":[
      "batch"
   ],
   "exporters":[
      "datadog"
   ],
   "dataType":"otlp",
   "dataMode":"trace",
   "dataRate":1000,
   "avgCpu":30.723319623252387,
   "avgMem":74.24590506666667,
   "commitId":"dummy_commit",
   "collectionPeriod":10,
   "testingAmi":"soaking_linux"
}
```
</details>

<details>
    <summary>5000 TPS</summary>

```json
{
   "testcase":"datadog_exporter_trace_mock",
   "instanceType":"m5.2xlarge",
   "receivers":[
      "otlp"
   ],
   "processors":[
      "batch"
   ],
   "exporters":[
      "datadog"
   ],
   "dataType":"otlp",
   "dataMode":"trace",
   "dataRate":5000,
   "avgCpu":126.07871496444284,
   "avgMem":90.68038826666667,
   "commitId":"dummy_commit",
   "collectionPeriod":10,
   "testingAmi":"soaking_linux"
}
```

</details>

--- 
cc @mxiamxia @mraditya

**Comment by vasireddy99** [comment]
Closing this issue as the expected results were submitted. Please reopen the issue for any questions/concerns
