### ISSUE TITLE
Update sdk used by spark app

### ISSUE THREAD

**Issue by jefchien** [aws-observability/aws-otel-collector-test-framework#397]
Similar to https://github.com/aws-observability/aws-otel-test-framework/pull/321/files
It currently uses 1.4.1 and the SDK is as of now on 1.9.0 https://github.com/open-telemetry/opentelemetry-java/releases
There are quite a few breaking changes, so consider taking it a step at a time.

https://github.com/open-telemetry/opentelemetry-java/discussions/3506

**Comment by vasireddy99** [comment]
The sample app used in the framework is up-to date. Closing this issue since the spark sample app is removed from the ` aws-otel-test-framework` repo to avoid the dedup.

 * https://github.com/aws-observability/aws-otel-test-framework/pull/527
