### ISSUE TITLE
Adot operator orphaned resources causing failed build

### ISSUE THREAD

**Issue by aateeqi** [aws-observability/aws-otel-collector-test-framework#431]
During release of [0.15.1](https://github.com/aws-observability/aws-otel-collector/actions/runs/1556085261/attempts/4), orphaned resources from `adot-operator-cert-manager` was failing the build. This was temporarily resolved by using kubectl to find and delete resources.

**Comment by jefchien** [comment]
The `adot-operator` tests deploy both the cert-manager and the operator itself as part of two helm releases. The first issue we encountered was that the cert-manager resources already existed within the namespace and got `Error: cannot re-use a name that is still in use`. To resolve this, we deleted the `cert-manager` namespace. This allowed a new cert-manager to be created in a subsequent run. It seems like a previous run hadn't successfully destroyed the resources within the namespace.

The next issue we ran into was with the `opentelemetry-operator-system` namespace. A previous run hadn't been destroyed. Deleted the namespace. Had to manually delete the orphans.
```
kubectl delete clusterrole opentelemetry-operator-manager-role 
kubectl delete clusterrole opentelemetry-operator-metrics-reader
kubectl delete clusterrole opentelemetry-operator-proxy-role
kubectl delete clusterrolebinding opentelemetry-operator-manager-rolebinding 
kubectl delete clusterrolebinding opentelemetry-operator-proxy-rolebinding  
kubectl delete mutatingwebhookconfiguration opentelemetry-operator-mutating-webhook-configuration 
kubectl delete validatingwebhookconfiguration opentelemetry-operator-validating-webhook-configuration
```

After that, the tests were able to create their resources again.

**Comment by vasireddy99** [comment]
Closing this issue.

**Comment by vasireddy99** [comment]
Closing this issue.
