### ISSUE TITLE
Upgrade log4j dependency version

### ISSUE THREAD

**Issue by aateeqi** [aws-observability/aws-otel-collector-test-framework#439]
Based on https://logging.apache.org/log4j/2.x/security.html, we should update our log4j version to a safe version

https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/load-generator/build.gradle#L52-L53
https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/validator/build.gradle#L38-L39

**Comment by sethAmazon** [comment]
Removed internal link
