### ISSUE TITLE
Broken link in readme "The mechanism of testing framework"

### ISSUE THREAD

**Issue by rltoSD** [aws-observability/aws-otel-collector-test-framework#444]
https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/README.md
<img width="813" alt="image" src="https://user-images.githubusercontent.com/50217652/146530710-6c00ce33-7753-49eb-a662-482855671c98.png">
I believe that this is a broken link in the readme 

"we only validate if the data is received but not the data accuracy. [The mechanism of testing framework](docs/mechanism-of-testing-framework.md)"

are we supposed to redirect it to 

docs/testing-framework-design.md ?

**Comment by jefchien** [comment]
Yeah it looks like it was introduced in https://github.com/aws-observability/aws-otel-test-framework/commit/75271183d6fd0e5dfd89346cabcc76bbad0ebecd#diff-317d463c98c7b41aeefc76d17ad1300b2a443aea5919e7d51e45dd3d5cbe371d. I think it does make sense to change it to https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/docs/testing-framework-design.md

**Comment by rltoSD** [comment]
Closed as it has been resolved
