### ISSUE TITLE
Update sample-apps in the test-framework

### ISSUE THREAD

**Issue by vasireddy99** [aws-observability/aws-otel-collector-test-framework#497]
The current sample apps in the test framework doesn't include recent changes, hence outdated.

- prometheus-sample-app
- spark

CC : @jefchien

**Comment by bryan-aguilar** [comment]
CI/CD for sample apps under test is now in place. https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/.github/workflows/update-test-images.yml
