### ISSUE TITLE
Unable to Test `otlp_grpc_exporter_cw_amp_xray_ecs` in ECS Environment

### ISSUE THREAD

**Issue by erichsueh3** [aws-observability/aws-otel-collector-test-framework#605]
I am trying to run the test `otlp_grpc_exporter_cw_amp_xray_ecs`, but have run into multiple errors. The first issue is an issue with setting up the s3 buckets.

Steps to reproduce this error:
1. run `cd terraform/setup && terraform init && terraform apply -auto-approve` from [here](https://github.com/open-o11y/aws-otel-test-framework/blob/terraform/docs/run-testing-framework.md#212-run-setup). The error is
```
Error: Value for unconfigurable attribute

with aws_s3_bucket.example,
on main.tf line 1, in resource "aws_s3_bucket" "example":
1: resource "aws_s3_bucket" "example" {

Can't configure a value for "acl": its value will be decided automatically based on the result of applying this configuration.

```

This is due to the [terraform version 4 upgrade](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#acl-argument) and new resources need to be made for `acl`, `server_side_encryption_configuration `, and `versioning`.

After this first issue is resolved, `setup` and `imagebuild` work fine, though `imagebuild` gives an error but still builds and pushes all images to the ECR except the `jaeger-zipkin`sample-app`. It also gives a `local-exec provisioner error`, that seems to be the cause of the errors that follow as well.

Steps to reproduce this error:
1. run `cd terraform/setup && terraform init && terraform apply -auto-approve`
2. run `cd terraform/imagebuild && terraform init && terraform apply -auto-approve`
```
│ Error: local-exec provisioner error
│ 
│   with null_resource.build_and_push_sample_apps[0],
│   on main.tf line 58, in resource "null_resource" "build_and_push_sample_apps":
│   58:   provisioner "local-exec" {
│ 
│ Error running command 'docker build -t
│ 195181405982.dkr.ecr.us-west-2.amazonaws.com/otel-test/sample-apps:jaeger-zipkin-sample-app-latest
│ ../../sample-apps/jaeger-zipkin-sample-app/': exit status 1. Output: #1 [internal] load build definition
│ from Dockerfile
...
...
```

Then, when running the test, the test setup eventually hangs on retrying to create a validator. 

Steps to reproduce this error:
1. run `cd terraform/setup && terraform init && terraform apply -auto-approve`
2. run `cd terraform/imagebuild && terraform init && terraform apply -auto-approve`
3. run ` cd terraform/ecs && terraform init && terraform apply -auto-approve \
    -var="aoc_image_repo={{the docker image repo name you just pushed}}" \
    -var="aoc_version={{the aoc binary version}}" \
    -var="testcase=../testcases/otlp_grpc_exporter_cw_amp_xray_ecs" \
    -var-file="../testcases/otlp_grpc_exporter_cw_amp_xray_ecs/parameters.tfvars"`
```
module.validator[0].null_resource.validator: Still creating... [30s elapsed]
module.validator[0].null_resource.validator (local-exec): validator_1  | 10:16:45.371 [main] INFO  com.amazon.aoc.helpers.RetryHelper - retry attempt left : 38
module.validator[0].null_resource.validator: Still creating... [40s elapsed]
...
```

This will last until you `Ctrl+C`, at which point you get this error:
```
│ Error: local-exec provisioner error
│ 
│   with module.validator[0].null_resource.validator,
│   on ../validation/main.tf line 84, in resource "null_resource" "validator":
│   84:   provisioner "local-exec" {
│ 
│ Error running command 'docker-compose -f validator_docker_compose.yml down
│ docker-compose -f validator_docker_compose.yml build
│ docker-compose -f validator_docker_compose.yml up --abort-on-container-exit
│ ': signal: killed. Output: Container ecs_validator_1  Stopping
```

**Comment by vasireddy99** [comment]
This error seems familiar, do you have docker running on the setup?. I'd try to run `docker` in background before running the test case. :)

**Comment by erichsueh3** [comment]
> This error seems familiar, do you have docker running on the setup?. I'd try to run `docker` in background before running the test case. :)

Unfortunately running the test case with `docker` running in the background still gives me the same error.

**Comment by vasireddy99** [comment]
Closing this issue since we can run the tests in ECS environment.
