### ISSUE TITLE
Only use default validation template for all the languages

### ISSUE THREAD

**Issue by bhautikpip** [aws-observability/aws-otel-collector-test-framework#613]
Currently, for expected trace template we have separate templates for `go`, `js`, `springboot` and `spark` applications [here](https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/validator/src/main/resources/expected-data-template). We also have default templates for HTTP and AWS trace. I think we should use only and only default templates and SDK language specific templates. This would help us to maintain better and enforce language parity between data models of various SDK languages. This might require minor changes in some sample app for respective SDKs. I'm opening this issue to track this effort.

Necessary pre-work: https://github.com/aws-observability/aws-otel-ops/issues/123

**Comment by humivo** [comment]
There is now a default validation template for all SDK languages (Python, Go, JS, Java so far).  The validation template can be found [here](https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/validator/src/main/resources/expected-data-template/standard)

**Comment by humivo** [comment]
Closing this issue as the default validation template has been created and is currently working as expected.
