### ISSUE TITLE
Deploying EKS cluster through terraform

### ISSUE THREAD

**Issue by Kausik-A** [aws-observability/aws-otel-collector-test-framework#624]
**Description**

One of the steps in the testing framework is the [deployment of an EKS cluster with ADOT and run various test cases](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/docs/run-testing-framework.md#24-run-in-eks). This involves manually deploying an EKS cluster on the integ account. We need to fix two of the issues

1. Automate the deployment of EKS through Terraform.
2.Fix the test-framework so that it can run on any AWS account.

**Comment by bryan-aguilar** [comment]
EKS Cluster deployment automation is now done through the CDK. See `cdk_infra` directory for app.
