### ISSUE TITLE
Pin default operator_image and operator_helm_chart versions

### ISSUE THREAD

**Issue by Kausik-A** [aws-observability/aws-otel-collector-test-framework#707]
### Context

This [ PR](https://github.com/aws-observability/aws-otel-test-framework/pull/706)  for `branch release/v0.17.x` locks the operator ECR image to `v0.45.0` and pinned `opentelemetry-operator` helm chart to `0.6.4`.  These are defined in `variables.tf` under [here](https://github.com/aws-observability/aws-otel-test-framework/blob/32f20b3e2c1f033633990b8acfcc03dd1b263c2b/terraform/eks/variables.tf#L59).

### Issues to work on
 For further releases we need to dynamically update these variables to test the `collector` to the right version of the `operator`. As we port these changes to the main terraform we have to:
 
 1. Set default values to `latest` ( to get the latest versions of the operator and helm chart )
 2. Update the workflow to pass the desired variables through CLI.

**Comment by bryan-aguilar** [comment]
This issue is no longer required. Operator versions are now derived from the collector go.mod file during the CI setup process.
