### ISSUE TITLE
Java package imports broken in load generator 

### ISSUE THREAD

**Issue by bryan-aguilar** [aws-observability/aws-otel-collector-test-framework#736]
PRs #721, #715, #714, #691 are failing due to a breaking change introduced in the upstream java release [`v1.15.0`](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.15.0).

```
BREAKING: merge all stable OTLP exporters into opentelemetry-exporter-otlp. opentelemetry-exporter-otlp-trace, opentelemetry-exporter-otlp-metrics, opentelemetry-exporter-otlp-http-trace, and opentelemetry-exporter-otlp-http-metrics are no longer published and their contents have been merged into a single artifact.
BREAKING: merge log OTLP exporters into opentelemetry-exporter-otlp-logs. opentelemetry-exporter-otlp-http-logs is no longer published and its contents have been merged into a single artifact.
```

Additionally:

- [x] Fix issue: https://github.com/aws-observability/aws-otel-test-framework/issues/771
- [x] Fix issue: `--dataRate` parameter is currently not generating output as described in `readme`.
- [x] Add flexibility to create multiple `metrics` as well multiple `datapoints`.
- [x] Update Docker Image in Public ECR.

**Comment by PaurushGarg** [comment]
Closing this issue, as relevant PR for this issue has been merged now.
