### ISSUE TITLE
Issue : Trouble setting up the fargate-integ-test cluster.

### ISSUE THREAD

**Issue by vasireddy99** [aws-observability/aws-otel-collector-test-framework#805]
The [fargate_setup](https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/terraform/eks_fargate_setup) for the setting up EKS Fargate cluster is leading to the following errors. This is a blocker for running eks tests cases in fargate. 

 * Unsupported terraform version
 * `Error: Waiting for rollout to finish: 0 of 1 updated replicas are available...`

Testcases : 

 * [eks_containerinsights_fargate](https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/terraform/testcases/eks_containerinsights_fargate)
 * [eks_containerinsights_fargate_metric](https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/terraform/testcases/eks_containerinsights_fargate_metric)

**Comment by bryan-aguilar** [comment]
Going to close this now that there is a new CDK based EKS Cluster setup framework located in `cdk_infra`.
